sentiment_analysis/README.md

- Remove redundant info
- Fix hyperlink

Fix readme instructions for sentiment analysis task

---

translation/download_data.sh

The test data appears to have moved. Updated the links with the current location.

Fix download links for translation test data.

---

translation/download_data.sh

Fix transformer download.

---

speech_recognition/pytorch/train.py

__print__ statements are a Syntax Error in Python 3.

print() is a function in Python 3

---

.gitmodules

This adds the community repo as a sub-module for the reference repo.

Adding community submodule

---

translation/data_download.py

This branch is created from https://github.com/mlperf/reference/pull/77 hence diff shows changes from both. I have not made changes independently since the dead code used lot of tf based apis

Tf independent download of dataset in data_download.py

---

.gitmodules
object_detection/caffe2/Dockerfile

This has not been run to convergence, but it successfully completed an epoch.

update object detection to pytorch 0.4.1, which contains caffe2

---

reinforcement/tensorflow/minigo/loop_init.py
reinforcement/tensorflow/minigo/loop_train_eval.py
reinforcement/tensorflow/minigo/requirements.txt

adding the logging for minigo. This PR uses Taylor's package so it should be able to merge as it is. Thanks!

adding minigo logging

---

translation/tensorflow/transformer/model/beam_search.py
translation/tensorflow/transformer/model/transformer.py
translation/tensorflow/transformer/transformer_main.py

- remove batch-specific values, log only hyperparams for beam search
- fix typo

Fix Transformer logging bugs

---

object_detection/caffe2/Dockerfile

fix docker setup for object detection

---

rnn_translator/README.md
rnn_translator/pytorch/README.md
rnn_translator/pytorch/run.sh

Proposed changes:
- ~made run.sh and run_and_time.sh executable~
- ~fixed path to the training data in pytorch/README.md~
- ~removed pycache directories and binary cache files~
- Changed BLEU in README files and in run.sh to 21.80 (it's the value set in run_and_time.sh)
Edit: I rebased this PR, striked out changes were already submitted with previous PRs, the only thing left is change of BLEU score in README filse and in run.sh.

[rnn_translator] Minor changes in the code

---

.gitmodules
compliance/verify_submission/README.md
compliance/verify_submission/crypto_requirements.txt
compliance/verify_submission/examples/example_report.txt
compliance/verify_submission/mlperf_submission_helper/checks.py
compliance/verify_submission/mlperf_submission_helper/constants.py
compliance/verify_submission/mlperf_submission_helper/crypto.py
compliance/verify_submission/mlperf_submission_helper/report.py
compliance/verify_submission/mlperf_submission_helper/test_crypto.py
compliance/verify_submission/mlperf_submission_helper/utils.py
compliance/verify_submission/mlperf_submission_helper/verify_submission.py

This adds initial commits of submission helper scripts for submission verification/extraction/encryption/decryption.

Add submission helper

---

compliance/mlperf_compliance/tf_mlperf_log.py

Found that cannot run image_classification with multiple GPUs. So tried to fix the failure.

fix failure when run image_classification with multiple GPUs.

---

compliance/verify_submission/mlperf_submission_helper/checks.py
compliance/verify_submission/mlperf_submission_helper/checks_test.py
compliance/verify_submission/mlperf_submission_helper/constants.py
compliance/verify_submission/mlperf_submission_helper/crypto.py
compliance/verify_submission/mlperf_submission_helper/report.py
compliance/verify_submission/mlperf_submission_helper/unittest_files/10_mixed_results/result_0.txt
compliance/verify_submission/mlperf_submission_helper/unittest_files/10_mixed_results/result_1.txt
compliance/verify_submission/mlperf_submission_helper/unittest_files/10_mixed_results/result_2.txt
compliance/verify_submission/mlperf_submission_helper/unittest_files/10_mixed_results/result_3.txt
compliance/verify_submission/mlperf_submission_helper/unittest_files/10_mixed_results/result_4.txt
compliance/verify_submission/mlperf_submission_helper/unittest_files/10_mixed_results/result_5.txt
compliance/verify_submission/mlperf_submission_helper/unittest_files/10_mixed_results/result_6.txt
compliance/verify_submission/mlperf_submission_helper/unittest_files/10_mixed_results/result_7.txt
compliance/verify_submission/mlperf_submission_helper/unittest_files/10_mixed_results/result_8.txt
compliance/verify_submission/mlperf_submission_helper/unittest_files/10_mixed_results/result_9.txt
compliance/verify_submission/mlperf_submission_helper/utils.py
compliance/verify_submission/mlperf_submission_helper/verify_submission.py

This is PR #200 with merge conflicts resolved.

compliance checker rework

---

data_generation/fractal_graph_expansions/README.md
data_generation/fractal_graph_expansions/graph_analysis.py
data_generation/fractal_graph_expansions/graph_analysis_test.py
data_generation/fractal_graph_expansions/graph_expansion.py
data_generation/fractal_graph_expansions/graph_expansion_test.py
data_generation/fractal_graph_expansions/graph_reduction.py
data_generation/fractal_graph_expansions/graph_reduction_test.py
data_generation/fractal_graph_expansions/random_matrix_ops.py
data_generation/fractal_graph_expansions/random_matrix_ops_test.py
data_generation/fractal_graph_expansions/run.sh
data_generation/fractal_graph_expansions/run_expansion.py
data_generation/fractal_graph_expansions/test_util.py
data_generation/fractal_graph_expansions/test_util_test.py
data_generation/fractal_graph_expansions/util.py
data_generation/fractal_graph_expansions/util_test.py

kronecker expansion of the movielens dataset

adding code for data generation

---

data_generation/fractal_graph_expansions/README.md

Corrects two typos about data set sizes

Correct typos in read me for data generation.

---

single_stage_detector/Dockerfile
single_stage_detector/requirements.txt
single_stage_detector/ssd/README.md
single_stage_detector/ssd/bind_launch.py
single_stage_detector/ssd/config_DGX1_32.sh
single_stage_detector/ssd/config_DGX1_multinode.sh
single_stage_detector/ssd/config_DGX1_singlenode.sh
single_stage_detector/ssd/mlperf_logger.py
single_stage_detector/ssd/run.sub
single_stage_detector/ssd/run_and_time.sh
single_stage_detector/ssd/ssd300.py
single_stage_detector/ssd/train.py

Addresses [mlperf/policies#173](https://github.com/mlperf/policies/issues/173)
Changes:
* accuracy threshold raised to 0.23mAP
* more parameters added e.g learning rate, warmup ,…
* multi-gpu and multi-node support added
* RNG seeding and logging compliant with latest MLPerf rules
* container updated to latest PyTorch 1.0.1
* mlperf-compliance updated to 0.0.10
* README modified

SSD multiGPU reference + quality change (21.2 to 23)

---

language_model/tensorflow/bert/README.md

Updating readme file to reflect latest stoping conditions and command lines

[BERT] update README

---

single_stage_detector/Dockerfile
single_stage_detector/requirements.txt
single_stage_detector/ssd/mlperf_logger.py
single_stage_detector/ssd/ssd300.py
single_stage_detector/ssd/train.py
single_stage_detector/ssd/utils.py

This PR is based on https://github.com/mlperf/training/pull/367 but fixes syntax errors and adds missing keys

[SSD] Update logging to v0.7

---

single_stage_detector/ssd/train.py
single_stage_detector/ssd/utils.py

Improved training logging and parametrized the following values:
* `--weight-decay`
* `--num-cropping-iterations`
* `--nms-valid-thresh`
* `--log-interval`
depends on https://github.com/mlperf/training/pull/416

[SSD] Parametrized several values

---

single_stage_detector/ssd/train.py
single_stage_detector/ssd/utils.py

Added batch evaluation to speeds up evaluation cycles, and the following flags to improve quality of life:
* `--val-interval`
* `--val-batch-size`
depends on https://github.com/mlperf/training/pull/418

[SSD] Support for batch evaluation

---

single_stage_detector/ssd/train.py

Added gradient accumulation support using the flag `--batch-splits` (split batch into N fragments)
depends on https://github.com/mlperf/training/pull/420

[SSD] Added gradient accumulation support

---

single_stage_detector/ssd/train.py

To close: https://github.com/mlperf/training_policies/issues/396

[SSD] Updated eval schedule to every 5th epoch

---

sentiment_analysis/README.md

benchmark is out of date and not part of MLPerf. Adjusting readme accordingly.

Updating readme to indicate deprecation

---

image_segmentation/pytorch/runtime/training.py

Fix evaluation schedule in cases that start_eval_at % evaluate_every != 0 (for example in GBS=32 case)

[UNET3D] Fix evaluation schedule

---

language_model/tensorflow/bert/README.md

Fix issue 462 - missing BERT input files.

Fix links to BERT input files

---

language_model/tensorflow/bert/README.md

[BERT] fix typos

---

rnn_speech_recognition/pytorch/common/data/features.py

[RNN-T] SpectAugment masks the last row/column

---

single_stage_detector/requirements.txt
single_stage_detector/scripts/pth_to_onnx.py
single_stage_detector/ssd/coco_eval.py
single_stage_detector/ssd/engine.py
single_stage_detector/ssd/train.py

- Changed the default lr to something that works with ADAM
- Synced the the onnx conversion script with the latest model changes
- Cleaned up CocoEvaluator implementation

[RetinaNet]: General fixes

---

single_stage_detector/README.md

changing capitalization

---

reinforcement/README.md

Issue https://github.com/mlcommons/training/issues/563 - forcing this one in fast in order to have correct numbers for v2.0 press activity, but we should revisit the complete documentation later.

Fix 9x9 to 19x19

---

object_detection/Dockerfile

This PR will fix the crash when building the mrcnn docker

[MRCNN] Fix docker build issue

---

recommendation_v2/torchrec_dlrm/Dockerfile
recommendation_v2/torchrec_dlrm/dlrm_main.py
recommendation_v2/torchrec_dlrm/mlperf_logging_utils.py
recommendation_v2/torchrec_dlrm/requirements.txt

Author: Jan Lasek (jlasek_at_nvidia.com)
Reopening https://github.com/mlcommons/training/pull/615 after signing MLCommons CLA.

[DCNV2] Add MLPerf logging

---

recommendation_v2/torchrec_dlrm/README.MD

Author: Jan Lasek, Nvidia (jlasek_at_nvidia_dot_com)
I'm updating README dataset download link because the one currently provided doesn't work. Besides. this is a dedicated MLPerf link that Criteo would like us to use.

[DLRMv2_DCNv2] Update Criteo 1TB dataset download link

---

object_detection/README.md

Proposed fix for https://github.com/mlcommons/training/issues/431

ResNet50 -> ResNet-50 in all docs

---

.gitignore
single_stage_detector/Dockerfile
single_stage_detector/mlcube/README.md
single_stage_detector/mlcube/mlcube.yaml
single_stage_detector/requirements.txt
single_stage_detector/scripts/download_backbone.sh
single_stage_detector/scripts/download_openimages_mlperf.sh
single_stage_detector/ssd/check_logs.sh
single_stage_detector/ssd/run_and_time.sh

This PR contains the integration of SSD reference benchmark with MLCube, with this implementation users will have a new way to reproduce the benchmark and they could even execute the complete pipeline with a single command.
MLCube™ GitHub [repository](https://github.com/mlcommons/mlcube). MLCube™ [wiki](https://mlcommons.github.io/mlcube/).
* [Docker](https://www.docker.com/)
* [Python](https://www.python.org/)
```bash
virtualenv -p python3 ./env && source ./env/bin/activate && pip install mlcube-docker
git clone https://github.com/mlcommons/training && cd ./training/single_stage_detector
```
Go to mlcube directory and study what tasks MLCube implements.
```shell
cd ./mlcube
mlcube describe
```
Download dataset.
```shell
mlcube run --task=download_data -Pdocker.build_strategy=always
``` …

SSD benchmark with MLCube implementation

---

image_classification/README.md

@sgpyc I found a similar link.  Does this look right to you?  I'm trying to resolve https://github.com/mlcommons/training/issues/480.

Update link for original source

---

large_language_model/megatron-lm/README.md
large_language_model/megatron-lm/megatron/data/gpt_dataset.py
large_language_model/megatron-lm/megatron/training.py
large_language_model/megatron-lm/scripts/preprocess_val.sh

1. Disable document shuffling
2. Update keywords to match the logging [PR](https://github.com/mlcommons/logging/pull/303)
3. Update README for validation dataset preprocessing
4. Set benchmark name as "gpt3" to match logging PR

[GPT3] update megatron-LM reference

---

recommendation_v2/torchrec_dlrm/dlrm_main.py
recommendation_v2/torchrec_dlrm/requirements.txt

Prerequisite: https://github.com/mlcommons/logging/pull/309
cc @erichan1

[DLRM_DCNv2] Benchmark name in reference implementation

---

stable_diffusion/mlperf_logging_utils.py
stable_diffusion/requirements.txt

This PR along with https://github.com/mlcommons/logging/pull/357 should address https://github.com/mlcommons/logging/issues/351

[SD] log number of samples instead of number of iterations

---

graph_neural_network/Dockerfile

Update the docker compose file to use the reference implementation in the training repo instead of gltorch

GNN: update the docker compose file

---

graph_neural_network/Dockerfile
graph_neural_network/Dockerfile.h100
graph_neural_network/README.md

This draft PR adds an example Dockerfile for building and running GNN reference on H100 machines.

[GNN] Adds example building dockerfile for H100s. 

---

stable_diffusion/Dockerfile

Fixes https://github.com/mlcommons/training/issues/731

[SD] Added rclone to Dockerfile

---

graph_neural_network/README.md

added param count inside benchmark

added param count inside benchmark

---

graph_neural_network/download.py
graph_neural_network/download_igbh_full.sh

We moved IGB to another s3 bucket. This PR updates the download paths.

Updating IGB download paths
