mlcommons/training

- recommendation/pytorch/run_and_time.sh
I confirmed the Docker and from source instructions work with complete runs to the threshold. This should have no impact on performance.
> Fix run_an_time.sh for recommendation built from source

- reinforcement/tensorflow/minigo/yomi/simple_eval.py
flake8 testing of https://github.com/mlperf/reference on Python 3.6.3
$ __flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics__
```
./reinforcement/tensorflow/minigo/goparams.py:50:12: F821 undefined name 'BASE_DIR'
BASE_DIR = BASE_DIR.replace('$HOME', HOME)
^
./reinforcement/tensorflow/minigo/yomi/simple_eval.py:40:20: E999 SyntaxError: invalid syntax
if len(models) = 0:
^
./sentiment_analysis/paddle/train.py:149:40: E999 TabError: inconsistent use of tabs and spaces in indentation
train_loss_set.append(float(cost_val))
^
./speech_recognition/pytorch/train.py:74:79: E999 SyntaxError: invalid syntax
print "ERROR: GRU does not currently support activations other than tanh"
^
./translation/data_download.py:343:15: F821 undefined name 'six'
for k, v in …
```
> Fix Python syntax error

- recommendation/pytorch/requirements.txt
The pytorch implementation of the recommendation benchmark requires scipy and pandas.
> Added scipy and pandas to requirements.txt in /reference/recommendation

- recommendation/pytorch/Dockerfile
- recommendation/pytorch/README.md
- recommendation/pytorch/convert.py
- recommendation/pytorch/dataset.py
- recommendation/pytorch/ncf.py
- recommendation/pytorch/run_and_time.sh
This pull request addresses [mlperf/policies#14](https://github.com/mlperf/policies/issues/14) by increasing the number of negative samples from 100 to 999 for the recommendation benchmark and updating the threshold accordingly. The new threshold is a hit rate of 0.6289 at 10, which is based on the lowest hit rate achieved by the 5 random seeds:
```
seed
1    0.629786
2    0.633101
3    0.632241
4    0.628985
5    0.630992
Name: hit_rate, dtype: float64
```
[Here](https://github.com/mlperf/reference/files/2112584/n999_timing_output.txt) is the output using the new threshold with the 5 seeds.
Calculating validation accuracy was also improved to parallelize across CPUs, decreasing the validation time per epoch from ~90 seconds to ~53 seconds. Batch size also changed based on hyperparameter …
> Add more negative examples

- recommendation/pytorch/README.md
- recommendation/pytorch/dataset.py
- recommendation/pytorch/ncf.py
- recommendation/pytorch/run_and_time.sh
This pull request addresses a bug with the random seed in DataLoader workers. Rather than using numpy to generate indices for the random negative training examples, the code now uses torch, which correctly sets a different random seed for each worker. Previously, increasing the number of workers for the DataLoader dramatically decreased the final quality.
Additionally, the MLP part of the model includes an additional Dense layer to match the default of three from the [original paper](http://delivery.acm.org/10.1145/3060000/3052569/p173-he.pdf?ip=171.64.70.182&id=3052569&acc=ACTIVE%20SERVICE&key=AA86BE8B6928DDC7%2E0AF80552DEC4BA76%2E4D4702B0C3E38B35%2E4D4702B0C3E38B35&__acm__=1531261116_fc0ef27a681d1faed305ada95d675bda): 
> Without special mention, we employed three hidden layers for MLP; …
> Fix random seed in workers and add 1 more layer in the MLP

- compliance/mlperf_compliance/_gnmt_tags.py
- compliance/mlperf_compliance/_ssd_tags.py
- compliance/mlperf_compliance/_transformer_tags.py
- compliance/mlperf_compliance/mlperf_log.py
- compliance/mlperf_compliance/resnet_log_helper.py
- compliance/mlperf_compliance/tags.py
- compliance/mlperf_compliance/test_tag_set.py
- compliance/setup.py
I noticed that several PRs have merge conflicts due to the recent change in compliance utils structure. To make everyone's lives easier, I have pulled all of the changes into a util specific PR and will build 0.0.4 of the mlperf_compliance pip package once this PR is merged. That way you don't have to deal with resolving the merge confilcts; just add a line to requirements.txt
Notable changes:
GNMT: @szmigacz
https://github.com/mlperf/training/pull/157
* I changed some tag names in _gnmt_tags.py to match the tag format.
* I did not include the path manipulation for setting `ROOT_DIR_GNMT`. Please override that value in a main function.
SSD: @christ1ne 
https://github.com/mlperf/training/pull/159
* Just pulled in the expanded tag set. (Thanks for that!)
Transformer: @xyhuang
* Added …
> Pull in tag sets from various PRs

- compliance/mlperf_compliance/mlperf_log.py
- compliance/mlperf_compliance/tags.py
- compliance/setup.py
- image_classification/tensorflow/requirements.txt
- recommendation/pytorch/requirements.txt
- reinforcement/tensorflow/minigo/requirements.txt
This PR just fixes a couple inconsistencies in the logging util. I just figured this was a good time to do a bit of linting before building 0.0.5 so that the util includes the recent Transformer annotations.
> minor updates to mlperf logging util: mlperf_compliance==0.0.6

- translation/tensorflow/process_data.py
- translation/tensorflow/transformer/utils/dataset.py
Insert an additional tag in processed data filenames that indicates whether a file is generated in the "compile" step or "encode" step. Change filename matching pattern in dataset util to use only "encoded" files during training or evaluation. This change fixes the incorrect mixing of the 2 kinds of data in the input of training/evaluation, which causes errors.
Fixes #168
> Fix transformer input filename pattern matching

- compliance/mlperf_compliance/tags.py
- compliance/setup.py
This is to enable ssd logs to pass mlp_compliance by setting a new tag for checking for evaluations at iterations as the default evaluation tags are for evaluation at epochs.
> adding tag to handle evaluations by iterations

- translation/tensorflow/transformer/data_download.py
The file pattern in the train_input_fn and eval_input_fn under translation/tensorflow/transformer/utils/dataset.py requires the word `encoded` be present in the file names. When the files were downloaded using the data_download.py provided with transformer, the files do not have `encoded` as part of their string. Fixing the `data_download.py`  to match `process_data.py` similar to #173 ,  so one can run the transformer code without running into this issue
> data_download.py consistent with process_data.py for transformers

- single_stage_detector/Dockerfile
- single_stage_detector/ssd/config_DGX1_multinode.sh
- single_stage_detector/ssd/config_DGX1_singlenode.sh
- single_stage_detector/ssd/train.py
Resolves issues #290 and https://github.com/mlperf/training_policies/issues/210
Included changes:
- evaluation and LR decay are moved out of the train loop and are executed on epoch boundaries
- warmup argument is provided per epochs as float
- quote from the #290:
> The factor wb discussed in rule 9.1 will be calculated as this parameter times the number of non-empty images in an epoch (117266) divided by N_gpu*batch_size, and rounded down to the nearest integer.
- aligning configs to the changes
- Dockerfile cleanup
The convergence rate was tested and is ok.
> [single_stage_detector] evaluation, warmup and lr decay on epoch boundaries

- compliance/mllog/README.md
- compliance/mllog/__init__.py
- compliance/mllog/constants.py
- compliance/mllog/examples/__init__.py
- compliance/mllog/examples/dummy_example.py
- compliance/mllog/mllog.py
- compliance/mllog/test_mllog.py
- compliance/setup.py
- Changes in log format
- add call_site field to the log json to show the file and line no. info
- change time_ns to time_ms since ms was previously agreed also time() doesn't have enough precision
- Changes in MLLogger
- replace attributes log_info and log_file with a logging.Logger instance for full flexibility
- add stack_offset attribute for adjusting stack depth in finding call sites
- add clear_line attribute to allow clearing possible pre-existing texts in a log line
- Added a shared MLLogger instance at mllog package level
- Added readme
- Added a dummy example
- Added basic unit tests
- Updated setup.py
> Enhancements, fixings, and cleanups for mllog package

- single_stage_detector/download_resnet34_backbone.sh
- single_stage_detector/ssd/README.md
- single_stage_detector/ssd/base_model.py
- single_stage_detector/ssd/mlperf_logger.py
- single_stage_detector/ssd/ssd300.py
- single_stage_detector/ssd/train.py
Add the option to load pretrained weights from a local file with `--pretrained-backbone <PATH>`.
Updated README with pretrained weights information and download scripts
depends on https://github.com/mlperf/training/pull/416
> [SSD] Option to load pretrained weights from file

- image_classification/README.md
Documentation claims target accuracy is 74.9%.
This is not correct, it is 75.9%.
We should review for other errors.
> Changing accuracy target to be....accurate

- rnn_speech_recognition/pytorch/common/data/dali/sampler.py
The bucket sampling algorithm described in the [README](https://github.com/mlcommons/training/blob/8f7f74f88874ae85a58ddedd778c320739b37444/rnn_speech_recognition/pytorch/README.md#training-data-order) removes random samples from epoch to make epoch divisible by the batch size (point 4.ii).
Source has a bug, where the samples are not removed, but replaced by samples from the last bucket, that contains the longest samples:https://github.com/mlcommons/training/blob/8f7f74f88874ae85a58ddedd778c320739b37444/rnn_speech_recognition/pytorch/common/data/dali/sampler.py#L86
The bug has two impacts:
1. A negative impact on performance, as the longes samples are mixed with shorter samples. As result, more padding is needed.
2. It impacts sample randomness, as the longest samples are chosen more …
> [RNN-T] bucketing sampler fix

- image_segmentation/pytorch/README.md
- image_segmentation/pytorch/data_loading/data_loader.py
- image_segmentation/pytorch/main.py
- image_segmentation/pytorch/requirements.txt
- image_segmentation/pytorch/runtime/arguments.py
- image_segmentation/pytorch/runtime/training.py
Proposed changes:
- Restored multi-gpu (multi-device) training and evaluation
- `DistributedSampler` does not support `last batch padded` functionality, therefore `last batch dropped` is used.
- Readme was updated to accommodate the changes
- No changes in evaluation schedule are proposed - the dependency on revised `samples per epoch` still holds
- Fixed performance issues with gradient accumulation
> U-Net3D update for MLPerf 2.0

- object_detection/pytorch/tools/train_mlperf.py
Fix this crash:
```
Traceback (most recent call last):
File "tools/train_mlperf.py", line 309, in <module>
main()
File "tools/train_mlperf.py", line 298, in main
model, success = train(cfg, args.local_rank, args.distributed, args.disable_allreduce_for_logging, random_number_generator)
AttributeError: 'Namespace' object has no attribute 'disable_allreduce_for_logging
```
> [MRCNN] remove ununsed argument

- recommendation_v2/torchrec_dlrm/dlrm_main.py
Author: Jan Lasek, Nvidia (jlasek_at_nvidia.com)
There is parameter mismatch for Adagrad optimizer for embeddings and dense layers in the new DLRMv2 recommender benchmark.
As the dense layers and the embeddings employ PyTorch and FBGEMM Adagrad implementations, respectively, one needs to explicitly pass all relevant optimizer parameters in `apply_optimizer_in_backward` call:
* Currently FBGEMM uses `eps=1e-8` as [default here](https://github.com/pytorch/FBGEMM/blob/v0.3.2/fbgemm_gpu/fbgemm_gpu/split_table_batched_embeddings_ops.py#L218)
* On the other hand, PyTorch uses `eps=1e-10`, see [docs here](https://pytorch.org/docs/stable/generated/torch.optim.Adagrad.html#torch.optim.Adagrad).
This causes a mismatch between the two optimizer used that I'm fixing here.
> [DLRMv2] Align optimizer parameters for embeddings and dense layers

- recommendation_v2/torchrec_dlrm/dlrm_main.py
- recommendation_v2/torchrec_dlrm/requirements.txt
Author: Jan Lasek, Nvidia (jlasek_at_nvidia_dot_com)
I'm using the final name for the new recommender benchmark -- "DLRMv2" a.k.a. "dlrmv2". I'm also employing new constants for improved logging.
Prerequisite: merge https://github.com/mlcommons/logging/pull/297.
> [DLRMv2] Resolve benchmark name and use other constants for logging

- rnn_speech_recognition/pytorch/Dockerfile
RNN-T docker image stopped building because of an outdated APT repository and new protobuf package issues. This PR fixes that.
> Fix outdated RNN-T Dockerfile

- recommendation_v2/torchrec_dlrm/README.MD
Author: Jan Lasek, Nvidia (jlasek_at_nvidia_dot_com)
I'm updating the threshold value as the final decision was to use **0.80275**, see [Training Rules](https://github.com/mlcommons/training_policies/blob/master/training_rules.adoc#41-closed-division) or [compliance checker](https://github.com/mlcommons/logging/blob/ba76cad767d674f1475adfba18057e8c63d0a500/mlperf_logging/compliance_checker/training_3.0.0/closed_dlrmv2.yaml#L49-L54).
> [DLRMv2] Update target AUC in README

- image_segmentation/pytorch/data_loading/data_loader.py
- image_segmentation/pytorch/main.py
The DistributedSampler seed should be the same across all workers, else the data split is not exclusive. 
https://pytorch.org/docs/stable/data.html#torch.utils.data.distributed.DistributedSampler
Indeed, printing out the indexes read by each worker shows overlap (around 20% to 30%!)
It looks like the shuffling seeds might have been meant for this, but were not used. I took the first one to initialize the sampler. The seed will then be updated for each epoch by the call to `sampler.set_epoch()` already present in training.py.
> UNET3D - Change DistributedSampler seed to be same across all workers

- language_model/tensorflow/bert/README.md
- large_language_model/megatron-lm/README.md
We've switched S3 cloud storage providers to Cloudflare to take advantage of Cloudflare's edge infrastructure, which will provide much faster download speeds for everyone not close to the US East region. We're also rolling out a set of standard Rclone commands that are quick and easy to run to download data from our buckets.
> Update S3 download instructions

- single_stage_detector/.dockerignore
- single_stage_detector/mlcube/mlcube.yaml
- single_stage_detector/requirements.txt
- single_stage_detector/scripts/download_openimages_demo.sh
- single_stage_detector/ssd/run_demo.sh
This PR includes a small demo to execute the SSD benchmark.
```bash
virtualenv -p python3 ./env && source ./env/bin/activate && pip install mlcube-docker
git clone https://github.com/mlcommons/training && cd ./training/single_stage_detector
git fetch origin pull/683/head:feature/ssd_example && git checkout feature/ssd_example
```
Go to mlcube directory and study what tasks MLCube implements.
```shell
cd ./mlcube
mlcube describe
```
Download demo.
```shell
mlcube run --task=download_demo -Pdocker.build_strategy=always
```
Download model.
```shell
mlcube run --task=download_model -Pdocker.build_strategy=always
```
Run demo.
```shell
mlcube run --task=demo -Pdocker.build_strategy=always
```
You can execute the complete pipeline with one single command.
```shell
mlcube run …
```
> Add quick SSD demo

- graph_neural_network/README.md
- graph_neural_network/dist_train_rgnn.py
- graph_neural_network/train_rgnn_multi_gpu.py
> Add missing logging keys for GNN

- large_language_model/megatron-lm/megatron/training.py
> added train_samples keyword for compliance check

- README.md
1. Change submission from v40 to v41
2. Drop deprecated benchmarks
> Change submission date from v40 to v41

- llama2_70b_lora/README.md
This PR replaces the link to the old LLama 2 confidentiality notice agreement form (soon to be disabled) with a link to the new form that functions as the front-end for a new back-end system that streamlines the Member company agreement process.
> Update Llama2 Member download instructions

- large_language_model/megatron-lm/README.md
Addresses following issues - 
https://github.com/mlcommons/training/issues/653 
https://github.com/mlcommons/training/issues/669 
https://github.com/mlcommons/training/issues/673
https://github.com/mlcommons/training/issues/637
> Remove gs://mlperf-llm-public2/ dependency and make reproducibility instructions clear

- README.md
Parameter count in summary table - draft 1
> Parameter count in summary table

- large_language_model_pretraining/nemo/README.md
- large_language_model_pretraining/nemo/callbacks.py
- large_language_model_pretraining/nemo/pretrain_llama31.py
- large_language_model_pretraining/nemo/run_llama31.sh
- large_language_model_pretraining/nemo/utils/consolidate_data.sh
- large_language_model_pretraining/nemo/utils/preprocess.sh
- mixture_of_experts_pretraining/README.md
This PR includes the following changes: 
- Llama 3.1: 
1. Updated the validation dataset so that it now contains strictly only 5760 sequences. This impacts the preprocessing script, README downloading instructions, and pretraining script's dataset loading section. 
2. Updated logging to log number of sequences, instead of number of tokens. This impacts the README descriptions, pretrain launch script's arguments, and callback's logging. 
3. Updated the dataset location on the S3 bucket in the README. 
4. Added a knob `STEP_TIME_ATOL` so that, if a training step time is longer than this threshold, then we actively kill this job. Defaults to 2hrs per step. 
5. Updated how the checkpoints are resumed across different experiment partitions when we start from HF checkpoint. 
6. Updated the …
> [Llama 3.1] Updates dataset, logging, and checkpoint resume. 

- text_to_image/README.md
Previously, if a seed is not passed, one is picked randomly but is not logged.
Now it is explicitly picked randomly and logged
> [Flux.1] explicitly set and log seed

- text_to_image/README.md
This pr introduces changes to the validation to make it more uniform amongst submitters, making errors harder. Changes are as follows:
During a model forward step, the model attempts to denoise a latent. To do this, we take a latent from an image (will be our ground truth) and add noise to it. The amount of noise we add depends on the `timestep`, a value from 0 to 1. Naturally, the more noise we add, the harder the denoising task, and so the larger the loss we should expect.
For validation, we follow the flux paper. We 8 equally spaced timesteps from [0, 1) -> (0, 1/8, 2/8, 3/8, 4/8, 5/8, 6/8, 7/8) and try to sample equally from them.
This means we have to select one of these timesteps for each validation sample.
Currently, this is done dynamically at train time. If we let each sample …
> use more robust validation, defined at dataset level

- large_language_model_pretraining/nemo/README.md
The download instructions in one of the readme files directs folks to download Rclone for Windows "here" without a hyperlink. This PR adds the missing hyperlink.
> Add Rclone Windows install link to README.md

- single_stage_detector/ssd/run_and_time.sh
Dear MLCommons team,
I appreciate your work, which has helped me verify the training performance after applying hardware resource virtualization to our bare-metal server.
I want to validate the model training performance in a reasonable time on both virtualized and non-virtualized environments. However, this is very challenging with the default Open Images dataset and our relatively small GPUs in a single node. Thus, I made some changes to the performance evaluation script, which may help others with similar use cases.
This pull request modifies the `run_and_time.sh` of SSD training, and introduces the following changes:
- ~Added `DATASET` environment variable for dataset customization. This allows the script to run the training script with datasets other than the default Open Image …
> [single_stage_detector] Updated run_and_time.sh for customizing number of GPUs on single node

- text_to_image/README.md
The empty encodings download was missing
> add_empty_encodings_download
